// services/HttpClientBase.ts
import { authBridge } from './authBridge';

type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';

interface RequestOptions {
  /** Attach the bearer token and apply 401-refresh / logout handling. Default true. */
  auth?: boolean;
  /** Fallback message if the server provides none. */
  fallback?: string;
}

export abstract class HttpClientBase {
  protected baseUrl: string;

  constructor() {
    this.baseUrl = this.getBaseUrlFromConfig();
  }

  protected getBaseUrlFromConfig(): string {
    const appConfig = (window as unknown as Record<string, unknown>).__APP_CONFIG__ as Record<string, string> | undefined;
    if (import.meta.env.DEV) {
      // Dev: .env overrides the static placeholder in public/config.js
      return import.meta.env.VITE_API_BASE_URL || appConfig?.apiBaseUrl || "http://localhost:5245";
    }
    // Production: runtime config.js (generated by Docker entrypoint) always wins
    return appConfig?.apiBaseUrl || "http://localhost:5245";
  }

  protected get<T>(url: string): Promise<T> {
    return this.request<T>('GET', url, undefined, { fallback: "An unexpected error occurred while fetching data." });
  }

  protected post<T>(url: string, body: unknown): Promise<T> {
    return this.request<T>('POST', url, body, { fallback: "An unexpected error occurred while creating data." });
  }

  protected put(url: string, body: unknown): Promise<void> {
    return this.request<void>('PUT', url, body, { fallback: "An unexpected error occurred while updating data." });
  }

  protected putWithResponse<T>(url: string, body: unknown): Promise<T> {
    return this.request<T>('PUT', url, body, { fallback: "An unexpected error occurred while updating data." });
  }

  protected delete(url: string): Promise<void> {
    return this.request<void>('DELETE', url, undefined, { fallback: "An unexpected error occurred while deleting data." });
  }

  /**
   * Anonymous POST that bypasses bearer attachment and the 401-refresh/logout flow.
   * Used for login and token refresh, where a 401 means "bad credentials / expired refresh
   * token", not "session expired" — so it must not trigger a logout or a refresh loop.
   */
  protected postAnonymous<T>(url: string, body: unknown): Promise<T> {
    return this.request<T>('POST', url, body, { auth: false, fallback: "Authentication request failed." });
  }

  private buildHeaders(includeAuth: boolean): Record<string, string> {
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    if (includeAuth) {
      const token = authBridge.getAccessToken();
      if (token) headers["Authorization"] = `Bearer ${token}`;
    }
    return headers;
  }

  private async request<T>(method: HttpMethod, url: string, body: unknown, opts: RequestOptions): Promise<T> {
    const includeAuth = opts.auth !== false;
    const fullUrl = this.baseUrl + url;
    const serialized = body !== undefined ? JSON.stringify(body) : undefined;

    let response = await fetch(fullUrl, { method, headers: this.buildHeaders(includeAuth), body: serialized });

    // On an authenticated 401, try a single silent refresh and replay the request once.
    if (includeAuth && response.status === 401) {
      const refreshed = await authBridge.tryRefresh();
      if (refreshed) {
        response = await fetch(fullUrl, { method, headers: this.buildHeaders(true), body: serialized });
      }
    }

    if (!response.ok) {
      if (response.status === 401 && includeAuth) {
        authBridge.notifyUnauthorized();
        throw new Error("Your session has expired. Please sign in again.");
      }
      if (response.status === 403) {
        const { code, message } = await this.readProblem(response);
        authBridge.notifyForbidden(code);
        throw new Error(message || "You do not have permission to perform this action.");
      }
      const message = await this.extractErrorMessage(response, opts.fallback ?? "An unexpected error occurred.");
      throw new Error(message);
    }

    const text = await response.text();
    if (!text) return undefined as T;
    return JSON.parse(text) as T;
  }

  /** Read an RFC 7807 problem+json body, returning its `code` extension and best message. */
  private async readProblem(response: Response): Promise<{ code?: string; message?: string }> {
    try {
      const text = await response.text();
      if (!text) return {};
      const json = JSON.parse(text);
      return { code: json.code, message: json.detail || json.title || json.message };
    } catch {
      return {};
    }
  }

  private async extractErrorMessage(response: Response, fallback: string): Promise<string> {
    try {
      const text = await response.text();
      if (!text) return fallback;
      try {
        const json = JSON.parse(text);
        return json.error || json.message || json.detail || json.title || text;
      } catch {
        return text;
      }
    } catch {
      return fallback;
    }
  }
}
