// services/HttpClientBase.ts
export abstract class HttpClientBase {
    protected baseUrl: string;

    constructor() {
      this.baseUrl = this.getBaseUrlFromConfig();
    }
  
    protected getBaseUrlFromConfig(): string {
      const appConfig = (window as unknown as Record<string, unknown>).__APP_CONFIG__ as Record<string, string> | undefined;
      if (import.meta.env.DEV) {
        // Dev: .env overrides the static placeholder in public/config.js
        return import.meta.env.VITE_API_BASE_URL || appConfig?.apiBaseUrl || "http://localhost:5245";
      }
      // Production: runtime config.js (generated by Docker entrypoint) always wins
      return appConfig?.apiBaseUrl || "http://localhost:5245";
    }
  
    protected async get<T>(url: string): Promise<T> {
      const fullUrl = this.baseUrl + url;
      const response = await fetch(fullUrl, {
        method: "GET",
        headers: {
          "Content-Type": "application/json"
        }
      });
      if (!response.ok) {
        throw new Error("An unexpected error occurred while fetching data.");
      }
      return response.json();
    }
  
    protected async post<T>(url: string, body: unknown): Promise<T> {
      const fullUrl = this.baseUrl + url;
      const response = await fetch(fullUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(body)
      });
      if (!response.ok) {
        const message = await this.extractErrorMessage(response, "An unexpected error occurred while creating data.");
        throw new Error(message);
      }
      const text = await response.text();
      if (!text) return undefined as T;
      return JSON.parse(text) as T;
    }

    protected async put(url: string, body: unknown): Promise<void> {
      const fullUrl = this.baseUrl + url;
      const response = await fetch(fullUrl, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(body)
      });
      if (!response.ok) {
        const message = await this.extractErrorMessage(response, "An unexpected error occurred while updating data.");
        throw new Error(message);
      }
    }

    protected async putWithResponse<T>(url: string, body: unknown): Promise<T> {
      const fullUrl = this.baseUrl + url;
      const response = await fetch(fullUrl, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(body)
      });
      if (!response.ok) {
        const message = await this.extractErrorMessage(response, "An unexpected error occurred while updating data.");
        throw new Error(message);
      }
      return response.json();
    }

    protected async delete(url: string): Promise<void> {
      const fullUrl = this.baseUrl + url;
      const response = await fetch(fullUrl, {
        method: "DELETE",
        headers: {
          "Content-Type": "application/json"
        }
      });
      if (!response.ok) {
        const message = await this.extractErrorMessage(response, "An unexpected error occurred while deleting data.");
        throw new Error(message);
      }
    }

    private async extractErrorMessage(response: Response, fallback: string): Promise<string> {
      try {
        const text = await response.text();
        if (!text) return fallback;
        try {
          const json = JSON.parse(text);
          return json.error || json.message || json.title || text;
        } catch {
          return text;
        }
      } catch {
        return fallback;
      }
    }
  }
  