#!/usr/bin/env bash
# ============================================================================
# generate-ui-permissions.sh  —  WP-17C (UI: permission constants codegen)
# ============================================================================
#
# Generates app-ui/src/generated/permissions.ts FROM the access-control manifest
# (app-ui/src/generated/access-control-matrix.json, vendored from patient-care-super —
# canonical source: patient-care-super/docs/access-control-matrix.md).
#
# Why generate: the matrix is the single source of truth (WP-17). Hand-typing claim
# strings into hasClaim(...) / router meta invites typos and drift; a generated constants
# module makes every gate reference a compiler-checked symbol (vue-tsc fails on a bad name),
# and CI (WP-17D) regenerates + fails on diff. The Vitest no-drift test also asserts the
# generated constant set equals the manifest's claim set.
#
# Mirrors patient-care-api/tools/generate-permissions.sh: constant name = claim with the
# dots stripped (Patients.Delinquent.View -> PatientsDelinquentView).
#
# Determinism: byte-identical across runs (claims come pre-sorted from the manifest;
# no timestamp in the output — only the manifest semantic hash in the header).
#
# Usage:
#   tools/generate-ui-permissions.sh            (re)generate app-ui/src/generated/permissions.ts
#   tools/generate-ui-permissions.sh --check    regenerate to a temp file, diff against the
#                                               committed file; exit 1 on drift (for WP-17D CI)
#
# Exit codes: 0 ok/in-sync · 1 drift (--check) · 2 error
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$REPO_ROOT/app-ui/src/generated/access-control-matrix.json"
OUT="$REPO_ROOT/app-ui/src/generated/permissions.ts"
MODE="generate"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) MODE="check"; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required" >&2; exit 2; }
[[ -f "$MANIFEST" ]] || { echo "ERROR: manifest not found: $MANIFEST" >&2; exit 2; }

# NB: pipe jq through `tr -d '\r'` everywhere — the Windows jq build emits CRLF, and a stray
# CR inside a generated TS string literal would land in the committed file and trip --check.
HASH="$(jq -r '._meta.semanticHash' "$MANIFEST" | tr -d '\r')"
[[ -n "$HASH" && "$HASH" != "null" ]] || { echo "ERROR: manifest has no semanticHash" >&2; exit 2; }

emit() {
  cat <<EOF
// <auto-generated>
//   GENERATED by tools/generate-ui-permissions.sh from the access-control manifest
//   (app-ui/src/generated/access-control-matrix.json). DO NOT EDIT BY HAND.
//
//   To change permissions: edit the canonical matrix
//   (patient-care-super/docs/access-control-matrix.md), regenerate the manifest
//   (patient-care-super/tools/generate-access-manifest.sh), re-vendor
//   app-ui/src/generated/access-control-matrix.json, then re-run
//   tools/generate-ui-permissions.sh.
//
//   Access-control manifest semantic hash: $HASH
// </auto-generated>

/**
 * Compile-time constants for every Permission claim in the access-control matrix.
 * Use with the auth store / useClaims:
 *   hasClaim('Permission', Permissions.PatientsDelinquentView)
 *
 * Generated from the manifest; ACCESS_CONTROL_MANIFEST_HASH anchors the version and the
 * Vitest no-drift test asserts this set equals the manifest's claims.
 */
export const Permissions = {
EOF
  jq -r '.claims[] | .claim' "$MANIFEST" | tr -d '\r' \
    | while read -r claim; do
        name="$(printf '%s' "$claim" | tr -d '.')"
        printf '  %s: '\''%s'\'',\n' "$name" "$claim"
      done
  cat <<EOF
} as const;

/** Union of every generated permission-claim string value. */
export type Permission = (typeof Permissions)[keyof typeof Permissions];

/** Access-control manifest semantic hash this module was generated from (WP-17 anchor). */
export const ACCESS_CONTROL_MANIFEST_HASH = '$HASH';
EOF
}

if [[ "$MODE" == "check" ]]; then
  tmp="$(mktemp)"
  emit > "$tmp"
  if diff -u "$OUT" "$tmp" >/dev/null 2>&1; then
    echo "permissions.ts in sync with manifest ($HASH)"
    rm -f "$tmp"
    exit 0
  else
    echo "DRIFT: app-ui/src/generated/permissions.ts differs from manifest ($HASH)" >&2
    diff -u "$OUT" "$tmp" >&2 || true
    rm -f "$tmp"
    exit 1
  fi
fi

emit > "$OUT"
echo "wrote $OUT ($HASH)"
